### ISSUE TITLE
ONE likelihood not working as usual in v3.0?

### ISSUE THREAD

**Issue by lukashergt** [CobayaSampler/cobaya#111]
When replacing the Planck likelihoods with the `one` likelihood to normalize the Bayes ratios, I now get the error posted below. 

* In version 2.0.3 this used to work simply by replacing the likelihoods with the `one` likelihood. Now in version 3.0 I first need to delete all parameters derived from CLASS, such as `Omega_m` or `YHe` etc. Is that change intentional? 

* Additionally, CLASS in combination with the `one` likelihood rejects some `extra_args` such as `modes` or `n_t`.

I have posted example `.yaml` scripts for both these points below.

### yaml file

```yaml
likelihood:
  one:
params:
  logA:
    prior:
      min: 2.5
      max: 3.7
    drop: true
  A_s:
    value: 'lambda logA: 1e-10*np.exp(logA)'
  n_s:
    prior:
      min: 0.885
      max: 1.04
  theta_s_1e2:
    prior:
      min: 1.03
      max: 1.05
    drop: true
  100*theta_s:
    value: 'lambda theta_s_1e2: theta_s_1e2'
    derived: false
  omega_b:
    prior:
      min: 0.019
      max: 0.025
  omega_cdm:
    prior:
      min: 0.025
      max: 0.471
  m_ncdm:
    value: 0.06
    renames: mnu
  tau_reio:
    prior:
      min: 0.01
      max: 0.4
  YHe:
sampler:
  polychord:
    nlive: 50
theory:
  classy:
    extra_args:
      N_ncdm: 1
      N_ur: 2.0328

```

### corresponding error

```python
[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/home/hergtl/.virtualenvs/cobayaenv/bin/cobaya-run", line 8, in <module>
    sys.exit(run_script())
  File "/home/hergtl/.virtualenvs/cobayaenv/lib/python3.8/site-packages/cobaya/run.py", line 193, in run_script
    run(info)
  File "/home/hergtl/.virtualenvs/cobayaenv/lib/python3.8/site-packages/cobaya/run.py", line 87, in run
    sampler = sampler_class(updated_info[kinds.sampler][sampler_name],
  File "/home/hergtl/.virtualenvs/cobayaenv/lib/python3.8/site-packages/cobaya/sampler.py", line 257, in __init__
    self.initialize()
  File "/home/hergtl/.virtualenvs/cobayaenv/lib/python3.8/site-packages/cobaya/samplers/polychord/polychord.py", line 136, in initialize
    self.model.measure_and_set_speeds(n=self.measure_speeds)
  File "/home/hergtl/.virtualenvs/cobayaenv/lib/python3.8/site-packages/cobaya/model.py", line 1064, in measure_and_set_speeds
    if self.loglike(point, cached=False, return_derived=False) != -np.inf:
  File "/home/hergtl/.virtualenvs/cobayaenv/lib/python3.8/site-packages/cobaya/model.py", line 340, in loglike
    ret_value = self.loglikes(
  File "/home/hergtl/.virtualenvs/cobayaenv/lib/python3.8/site-packages/cobaya/model.py", line 306, in loglikes
    result = self.logps(input_params, return_derived=return_derived,
  File "/home/hergtl/.virtualenvs/cobayaenv/lib/python3.8/site-packages/cobaya/model.py", line 238, in logps
    compute_success = component.check_cache_and_compute(
  File "/home/hergtl/.virtualenvs/cobayaenv/lib/python3.8/site-packages/cobaya/theory.py", line 248, in check_cache_and_compute
    if self.calculate(state, want_derived, **params_values_dict) is False:
  File "/home/hergtl/.virtualenvs/cobayaenv/lib/python3.8/site-packages/cobaya/theories/classy/classy.py", line 403, in calculate
    d, d_extra = self._get_derived_all(derived_requested=want_derived)
  File "/home/hergtl/.virtualenvs/cobayaenv/lib/python3.8/site-packages/cobaya/theories/classy/classy.py", line 440, in _get_derived_all
    derived = {
  File "/home/hergtl/.virtualenvs/cobayaenv/lib/python3.8/site-packages/cobaya/theories/classy/classy.py", line 441, in <dictcomp>
    p: requested_and_extra[self.translate_param(p)] for p in self.output_params}
KeyError: 'YHe'
-------------------------------------------------------------
```

### yaml file

```yaml
likelihood:
  one:
params:
  logA:
    prior:
      min: 2.5
      max: 3.7
    drop: true
  A_s:
    value: 'lambda logA: 1e-10*np.exp(logA)'
  n_s:
    prior:
      min: 0.885
      max: 1.04
  r:
    prior:
      min: 0
      max: 1
  theta_s_1e2:
    prior:
      min: 1.03
      max: 1.05
    drop: true
  100*theta_s:
    value: 'lambda theta_s_1e2: theta_s_1e2'
    derived: false
  omega_b:
    prior:
      min: 0.019
      max: 0.025
  omega_cdm:
    prior:
      min: 0.025
      max: 0.471
  m_ncdm:
    value: 0.06
    renames: mnu
  tau_reio:
    prior:
      min: 0.01
      max: 0.4
  YHe:
sampler:
  polychord:
    nlive: 50
theory:
  classy:
    extra_args:
      N_ncdm: 1
      N_ur: 2.0328
      n_t: scc
      alpha_t: scc
```

### corresponding error

```python
[classy] *ERROR* Serious error setting parameters or computing results. The parameters passed were {'A_s': 3.461167025030708e-09, 'n_s': 0.9802541061990232, 'r': 0.7545275258802321, '100*theta_s': 1.0423552177349549, 'omega_b': 0.020159510760177544, 'omega_cdm': 0.19542197725796628, 'm_ncdm': 0.06, 'tau_reio': 0.39142871781203287} and {'N_ncdm': 1, 'N_ur': 2.0328, 'n_t': 'scc', 'alpha_t': 'scc', 'output': ''}. See original CLASS's error traceback below.

Traceback (most recent call last):
  File "/home/hergtl/.virtualenvs/cobayaenv/lib/python3.8/site-packages/cobaya/theories/classy/classy.py", line 352, in calculate
    self.classy.compute()
  File "classy.pyx", line 366, in classy.Class.compute
classy.CosmoSevereError: 

Error in Class: Class did not read input parameter(s): r, n_t, alpha_t
```

**Comment by JesusTorrado** [comment]
Hi @lukashergt 

The first issue should have been fixed by commit 7ede29

The second one is trickier to fix: it happens because when running with `one`, nothing is requested from CLASS, and CLASS has this behaviour of complaining when it gets parameters that it does not need (which only makes half sense, because when nothing is requested it should complain about all parameters, not just the tensor modes ones). There are a number of possible solutions/workarounds:

- Add the missing requests manually to `extra_args`: `{modes: "s,t", output: tCl}`. This workaround cannot be automatised: `one` does not and cannot know what the likelihoods it replaces are requesting.
- Modify Cobaya to ignore CLASS' `CosmoSevereError`, but that's quite dangerous, because it is defined by CLASS as a *configuration error*, so that if it fails at one evaluation it will keep failing for the rest.

Or maybe some other one? Cannot think of any more right now.
