### ISSUE TITLE
How to make a theory accept indefinite number of parameters

### ISSUE THREAD

**Issue by zhaoruiyang98** [CobayaSampler/cobaya#213]
Hi, 
I want to implement a theory class to compute the cross and auto correlation of multiple tracers.
Different tracers will have different but similar nuisance parameters (physical contents), and need some extra info about the survey properties.
In principle, I can implement theory classes separately for one or two or three tracers etc., but it appears too dirty.

Ideally I want only one theory class, and let likelihoods request auto or cross correlation function from theory by specifying the prefix string of nuisance parameters and the survey information, so that the theory class knows which sampler parameter it needs. This appears cleaner, but I don't have idea how to implement this.

Does cobaya support this feature?
Many thanks!

**Comment by JesusTorrado** [comment]
At first sight, this does not look too different from what we do right now for CAMB or CLASS, where the likelihood requests (including whatever extra specifications needed) what it needs via its `get_requirements` method, and the theory code has a method called `must_provide` that parses these requirements and decides what needs to be computed. You can take a look at the CLASS interface and its `must_provide` method here, that does just that: https://github.com/CobayaSampler/cobaya/blob/master/cobaya/theories/classy/classy.py (CAMB's is a bit more complex).

I may help to think first how would likelihoods specify what they need, and then try to think of how the `must_provide` method of the theory code would look like.

Closing since this is not an issue, but feel free to keep on commenting here if you have any specific question about this.

**Comment by zhaoruiyang98** [comment]
Thanks for your quick response!
If I understand it correctly, CAMB and CLASS specify the cosmological parameters via `get_can_support_params` and `get_can_provide_params`, is this right? Cosmological parameter names are specified prior to likelihood requests.
I guess it is possible to return new requirements (i.e. specify the name of parameters) in `must_provide`, or there exists simpler ways?

**Comment by zhaoruiyang98** [comment]
I wrote a piece of code as following, but the `params_values_dict` is empty and it raise a KeyError in `calculate`…

```python
# test.py
from cobaya.theory import Theory
from cobaya.likelihood import Likelihood

class MyTheory(Theory):
    def initialize(self):
        self._prefix_map = {}

    def must_provide(self, **requirements):
        extra_requires = {}
        for k, v in requirements.items():
            if k == 'correlation_func':
                prefix = v.get('prefix_name')
                self._prefix_map[prefix] = v.get('settings')
                for p in ('theta1', 'theta2'):
                    extra_requires[prefix +'_' + p] = None
        return extra_requires

    def calculate(self, state, want_derived=True, **params_values_dict):
        print(params_values_dict)
        # compute here ...
        for prefix in self._prefix_map:
            self.mpi_info(f"theta1={params_values_dict[prefix + '_' + 'theta1']},"
                f"theta={params_values_dict[prefix + '_' + 'theta2']}")
    
    def get_can_provide_methods(self):
        return {'correlation_func': self.get_correlation_func}
    
    def get_correlation_func(self, prefix_name):
        pass

class JustTest(Likelihood):
    def get_requirements(self):
        requires = {'correlation_func': {
            'prefix_name': self.prefix_name,
            'settings': self.settings
        }}
        return requires
    
    def calculate(self, state, want_derived=True, **params_values_dict):
        # request things from theory
        self.provider.get_correlation_func(self.prefix_name)
        state['logp'] = 0
```

```yaml
# JustTest.yaml
prefix_name:
settings:
```

```yaml
# test.yaml
theory:
  lss:
    class: test.MyTheory
    python_path: .
likelihood:
  NGC:
    class: test.JustTest
    python_path: .
    prefix_name: 'NGC'
    settings: 1
params:
  NGC_theta1:
    prior:
      min: 0
      max: 1
  NGC_theta2:
    prior:
      min: 0
      max: 1
sampler:
  evaluate:
```

**Comment by zhaoruiyang98** [comment]
Sorry for the inconvenience, I attached the debug file
```txt
 2021-11-01 23:20:43,661 [output] Output to be read-from/written-into folder '.', with prefix 'test'
 2021-11-01 23:20:43,689 [model] Parameters were assigned as follows:
 2021-11-01 23:20:43,689 [model] - NGC:
 2021-11-01 23:20:43,689 [model]      Input:  []
 2021-11-01 23:20:43,689 [model]      Output: []
 2021-11-01 23:20:43,689 [model] - lss:
 2021-11-01 23:20:43,690 [model]      Input:  []
 2021-11-01 23:20:43,690 [model]      Output: []
 2021-11-01 23:20:43,691 [model] Components will be computed in the order:
 2021-11-01 23:20:43,692 [model]  - [lss, NGC]
 2021-11-01 23:20:43,692 [model] Requirements will be calculated by these components:
 2021-11-01 23:20:43,692 [model] - correlation_func: lss
 2021-11-01 23:20:43,700 [evaluate] Initialized!
 2021-11-01 23:20:43,705 [evaluate] Looking for a reference point with non-zero prior.
 2021-11-01 23:20:43,705 [prior] Reference values or pdfs for some parameters were not provided. Sampling from the prior instead for those parameters.
 2021-11-01 23:20:43,705 [prior] Evaluating prior at array([0.71258902, 0.00708321])
 2021-11-01 23:20:43,706 [prior] Got logpriors = 0.0
 2021-11-01 23:20:43,706 [evaluate] Reference point:
   NGC_theta1 = 0.712589
   NGC_theta2 = 0.00708321
 2021-11-01 23:20:43,706 [evaluate] Evaluating prior and likelihoods...
 2021-11-01 23:20:43,706 [model] Posterior to be computed for parameters {'NGC_theta1': 0.7125890229310791, 'NGC_theta2': 0.007083206246829121}
 2021-11-01 23:20:43,706 [prior] Evaluating prior at array([0.71258902, 0.00708321])
 2021-11-01 23:20:43,706 [prior] Got logpriors = 0.0
 2021-11-01 23:20:43,706 [model] Got input parameters: {'NGC_theta1': 0.7125890229310791, 'NGC_theta2': 0.007083206246829121}
 2021-11-01 23:20:43,707 [lss] Got parameters {}
 2021-11-01 23:20:43,707 [lss] Computing new state
{}
 2021-11-01 23:20:43,708 [exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/home/ruiyang/miniconda3/envs/cobaya/bin/cobaya-run", line 8, in <module>
    sys.exit(run_script())
  File "/home/ruiyang/miniconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/run.py", line 216, in run_script
    run(info, **arguments.__dict__)
  File "/home/ruiyang/miniconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/run.py", line 157, in run
    sampler.run()
  File "/home/ruiyang/miniconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/samplers/evaluate/evaluate.py", line 66, in run
    self.logposterior = self.model.logposterior(reference_point)
  File "/home/ruiyang/miniconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/model.py", line 421, in logposterior
    cached=cached, make_finite=make_finite)
  File "/home/ruiyang/miniconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/model.py", line 311, in _loglikes_input_params
    make_finite=make_finite)
  File "/home/ruiyang/miniconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/model.py", line 247, in logps
    dependency_params=depend_list, cached=cached)
  File "/home/ruiyang/miniconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/theory.py", line 260, in check_cache_and_compute
    if self.calculate(state, want_derived, **params_values_dict) is False:
  File "/home/ruiyang/data/newsource/project/pybird/Test/mustprovide/test.py", line 22, in calculate
    self.mpi_info(f"theta1={params_values_dict[prefix + '_' + 'theta1']},"
KeyError: 'NGC_theta1'
-------------------------------------------------------------

 2021-11-01 23:20:43,708 [exception handler] Some unexpected ERROR occurred. You can see the exception information above.
We recommend trying to reproduce this error with 'debug:True' in the input.
If you cannot solve it yourself and need to report it, include the debug output,
which you can send it to a file setting 'debug_file:[some_file_name]'.
```

**Comment by JesusTorrado** [comment]
Where do you want your parameters to go? The theory or the likelihood? At the moment they are not assigned to anyone (what should raise an error, strange...)

In any of these cases, you have a number of options: add a `params` section to the defaults yaml of the corresponding component (or `get_defaults` method), or give them a class attribute `input_params=[list of parameters]`.

**Comment by zhaoruiyang98** [comment]
I want the parameters go into the theory.
I add a line below the `extra_requires[prefix +'_' + p] = None` : `self.input_params.append(prefix + '_' + p)` and now it works!
Thank you very much!
