### ISSUE TITLE
No path given to the Planck likelihood. Set the likelihood property 'path' or the common property 'packages_path'

### ISSUE THREAD

**Issue by Rockdeldiablo** [CobayaSampler/cobaya#217]
Hello everyone, i am a new user, i just installed cobaya and i was trying some trial run with a yaml generated with cobaya-cosmo-generator but i think i messed up with the installation. when i run cobaya-run first.yaml  i get the error

```
[classy] Importing *global* CLASS.
[classy] Initialized!
[planck_2018_lowl.tt] *ERROR* No path given to the Planck likelihood. Set the likelihood property 'path' or the common property 'packages_path'.
[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/home/pasquale/anaconda3/bin/cobaya-run", line 8, in <module>
    sys.exit(run_script())
   .....
  File "/home/pasquale/anaconda3/lib/python3.8/site-packages/cobaya/component.py", line 95, in __init__
    self.initialize()
  File "/home/pasquale/anaconda3/lib/python3.8/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 51, in initialize
    raise LoggedError(
cobaya.log.LoggedError: No path given to the Planck likelihood. Set the likelihood property 'path' or the common property 'packages_path'.
```
 the likelihoods   are in  /home/pasquale/anaconda3/lib/python3.8/site-packages/cobaya/likelihoods  

so i tried to modify the yaml file  by adding path like 
likelihood:
  path: /home/pasquale/anaconda3/lib/python3.8/site-packages/cobaya/likelihoods

but I get an invalid syntax error.

so I would like to ask what is the correct way to provide the likelihoods path and the data path to cobaya? thank you.

**Comment by cmbant** [comment]
Did you install the data files OK?

https://cobaya.readthedocs.io/en/latest/installation_cosmo.html

**Comment by Rockdeldiablo** [comment]
> 

i think i have messed up this part because i already have class installed with some modification in the background.c file that i wanted to use and i didn't want to install class again ( and at the time looked like the data were in /home/pasquale/anaconda3/lib/python3.8/site-packages/cobaya/likelihoods).

but when i run 
`cobaya-install --show-packages-path`
i get
 

> (Not currently set.)

**Comment by Rockdeldiablo** [comment]
ok i have run the command you have linked but I skipped class or camb but that didn't solve the issue? how do i set personalized folders for likelikoods, data and class? 


```
[output] Output to be read-from/written-into folder '.', with prefix 'first'
[prior] *WARNING* External prior 'SZ' loaded. Mind that it might not be normalized!
[classy] Importing *auto-installed* CLASS (but defaulting to *global*).
[classy] *ERROR* Either CLASS is not in the given folder, '/home/pasquale/Documents/les/cb/code/classy', or you have not compiled it.
[classy] Initialized!
[clik] Importing *auto-installed* clik (but defaulting to *global*).
Cannot use clik wrapper (cause = 'libcfitsio.so.8: cannot open shared object file: No such file or directory')
Cannot use clik_lensing wrapper (cause = 'libcfitsio.so.8: cannot open shared object file: No such file or directory')
[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/home/pasquale/anaconda3/lib/python3.8/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 70, in initialize
    else clik.clik(self.clik_file)
AttributeError: module 'clik' has no attribute 'clik'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pasquale/anaconda3/bin/cobaya-run", line 8, in <module>
    sys.exit(run_script())
  File "/home/pasquale/anaconda3/lib/python3.8/site-packages/cobaya/run.py", line 216, in run_script
    run(info, **arguments.__dict__)
  File "/home/pasquale/anaconda3/lib/python3.8/site-packages/cobaya/run.py", line 134, in run
    with Model(updated_info["params"], updated_info["likelihood"],
  File "/home/pasquale/anaconda3/lib/python3.8/site-packages/cobaya/model.py", line 152, in __init__
    self.likelihood = LikelihoodCollection(info_likelihood, theory=self.theory,
  File "/home/pasquale/anaconda3/lib/python3.8/site-packages/cobaya/likelihood.py", line 298, in __init__
    self.add_instance(name, like_class(info, packages_path=packages_path,
  File "/home/pasquale/anaconda3/lib/python3.8/site-packages/cobaya/likelihood.py", line 90, in __init__
    super().__init__(info, name=name, timing=timing,
  File "/home/pasquale/anaconda3/lib/python3.8/site-packages/cobaya/theory.py", line 65, in __init__
    super().__init__(info, name=name, timing=timing,
  File "/home/pasquale/anaconda3/lib/python3.8/site-packages/cobaya/component.py", line 95, in __init__
    self.initialize()
  File "/home/pasquale/anaconda3/lib/python3.8/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 71, in initialize
    except clik.lkl.CError:
AttributeError: module 'clik' has no attribute 'lkl'
```

**Comment by Rockdeldiablo** [comment]
solved, i reinstalled and the issue disappeared.
