### ISSUE TITLE
Unsupported pickle protocol

### ISSUE THREAD

**Issue by runburg** [CobayaSampler/cobaya#218]
Hi,

I'm trying to modify my job script so that I can get cobaya running on my local cluster. I've got a working sbatch script, but I want to be able to generate it using `cobaya-run-job` so that the .paramnames file is generated (if I understand how that works correctly).

The script I've got working is 
```
#!/bin/bash
#SBATCH --nodes=1
#SBATCH --partition=kill-exclusive
#SBATCH -J ex_job
# IF THIS IS SINGLE NODE MPI, CONSTRAINT IS NOT REQUIRED
#SBATCH --constraint="ib_qdr"
#SBATCH -t 24:00:00
# DLS - THIS IS NOT RECOMMENDED AS IT WILL NEGATIVELT IMPACT PEROFRMANCE 
##SBATCH --core-spec=0

# One of two ways to ask for tasks.  using ntasks is more flexible as 
# it does not seem this process is memory intensive
##SBATCH --nodes=1
##SBATCH --tasks-per-node=6

#SBATCH --ntasks=6	

#SBATCH --cpus-per-task=2
#SBATCH --exclusive
#SBATCH --mem=16G
#SBATCH --mail-type=BEGIN,END,FAIL,REQUEUE,TIME_LIMIT_80
#SBATCH --mail-user=runburg@hawaii.edu



# Configure the Intel MPI parameters 
#####  FOR QDR NETWORK  ############
export I_MPI_FABRICS=shm:tmi
export I_MPI_PMI_LIBRARY=/lib64/libpmi.so
### FOR QDR NETWORK #####
export FI_PROVIDER=psm
export FI_PSM_TAGGED_RMA=0
export FI_PSM_AM_MSG=1
export FI_PSM_UUID=`uuidgen`
###### ######## ###### ##

module purge
module load  lib/mpi4py/3.0.1-intel-2018.5.274-Python-3.7.2
#module load tools/Vim
module load lang/Anaconda3/2020.11
#module load lib/mpi4py
module load compiler/GCCcore/7.3.0


# build the application
module load lib/libfabric # required for MPI compile and should be loaded ###after the intel compiler

cd /home/runburg/neutrinos_and_dm
source activate cobaya

export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}

python3 -c "import cobaya; print('success')"
#cobaya-run classy_trial.yaml

time srun -n ${SLURM_NTASKS} cobaya-run -r cobaya_ex.yaml > /home/runburg/neutrinos_and_dm/scripts/ex_fewer_cores.log 2>&1
```

I changed my template to
```
#!/bin/bash
#SBATCH --nodes={NUMNODES}
#SBATCH --partition={QUEUE}
#SBATCH -J {JOBNAME}
#SBATCH --constraint="ib_qdr"
#SBATCH -t {WALLTIME}
##SBATCH --core-spec=0
##SBATCH --tasks-per-node=6
##SBATCH --ntasks=6	
##SBATCH --cpus-per-task=2
##SBATCH --mem=20G
#SBATCH --mail-type=BEGIN,END,FAIL,REQUEUE,TIME_LIMIT_80
#SBATCH --mail-user=runburg@hawaii.edu

###OpenMP settings:
###export OMP_NUM_THREADS={OMP}
###export OMP_PLACES=threads
###export OMP_PROC_BIND=spread

# Configure the Intel MPI parameters 
#####  FOR QDR NETWORK  ############
export I_MPI_FABRICS=shm:tmi
export I_MPI_PMI_LIBRARY=/lib64/libpmi.so
### FOR QDR NETWORK #####
export FI_PROVIDER=psm
export FI_PSM_TAGGED_RMA=0
export FI_PSM_AM_MSG=1
export FI_PSM_UUID=`uuidgen`
###### ######## ###### ##


###set things to be used by the python script, which extracts text from here with ##XX: ... ##
### command to use for each run in the batch
##RUN: time srun -n {NUMTASKS} {PROGRAM} {INI} > {JOBSCRIPTDIR}/{INIBASE}.log 2>&1 ##
### defaults for this script
##DEFAULT_qsub: sbatch ##
##DEFAULT_qdel: scancel ##
##DEFAULT_cores_per_node: 8 ##
##DEFAULT_chains_per_node: 4 ##
##DEFAULT_program: cobaya-run -r ##
##DEFAULT_walltime: 24:00:00 ##
##DEFAULT_queue: kill-exclusive ##

module purge
module load  lib/mpi4py/3.0.1-intel-2018.5.274-Python-3.7.2
#module load tools/Vim
module load lang/Anaconda3/2020.11
#module load lib/mpi4py
module load compiler/GCCcore/7.3.0


# build the application
module load lib/libfabric # required for MPI compile and should be loaded ###after the intel compiler

cd /home/runburg/neutrinos_and_dm
source activate cobaya

export OMP_NUM_THREADS={NUMSLOTS}

python3 -c "import cobaya; print('success')"

{COMMAND}
```
and the persistent issue I'm getting is 
```
(cobaya) [runburg@node-0051 neutrinos_and_dm]$ cobaya-run-job cobaya_ex.yaml 
Job parameters: 1 runs of 4 chains on 1 nodes, each node with 4 MPI chains, each chain using 2 OpenMP cores (8 cores per node)
Traceback (most recent call last):
  File "/home/runburg/.conda/envs/cobaya/bin/cobaya-run-job", line 8, in <module>
    sys.exit(run_single())
  File "/home/runburg/.conda/envs/cobaya/lib/python3.7/site-packages/cobaya/grid_tools/runMPI.py", line 21, in run_single
    jobqueue.submitJob(os.path.basename(ini[0]), ini, msg=True, **args.__dict__)
  File "/home/runburg/.conda/envs/cobaya/lib/python3.7/site-packages/cobaya/grid_tools/jobqueue.py", line 381, in submitJob
    addJobIndex(kwargs.get('batchPath'), j)
  File "/home/runburg/.conda/envs/cobaya/lib/python3.7/site-packages/cobaya/grid_tools/jobqueue.py", line 216, in addJobIndex
    index = loadJobIndex(batchPath)
  File "/home/runburg/.conda/envs/cobaya/lib/python3.7/site-packages/cobaya/grid_tools/jobqueue.py", line 194, in loadJobIndex
    return pickle.load(inp)
ValueError: unsupported pickle protocol: 5
```
Any help understanding this pickle would be great!

**Comment by JesusTorrado** [comment]
Hi @runburg 

This sort of error happens when you are trying to load a pickle file that was generated with a version of the `pickle` package newer than the one used at load. Are you resuming a job that you started somewhere else?

If not, try finding and deleting the `job_index.pyobj` file that should have been created in the output folder.

**Comment by runburg** [comment]
Ah okay so I got that working (had to delete `.pyobj`). But I'm confused, I thought `Cobaya-run-job` was supposed to generate the `.paramnames` file so that `GetDist` could recognize the chains for plotting, but I'm not seeing that.

Is there a different way to generate the file so that I can plot using existing chains?

Thanks!

**Comment by cmbant** [comment]
Cobaya does not produce .paramnames files - the information is in the yaml. GetDist should get the information from the yaml instead when loading Cobaya chains.

**Comment by runburg** [comment]
Ah got it. I was looking in the wrong place sorry!
