### ISSUE TITLE
AttributeError: module 'clik' has no attribute 'lkl'

### ISSUE THREAD

**Issue by Xx-Luffy-xX** [CobayaSampler/cobaya#291]
I get this error and I can't seem to find why. I use a fresh install, following the instructions closely. I describe my setup and how I get the error and put all output below.

Thanks, Tal.

---
I've carried a fresh install of Cobaya in a new conda environment:

`conda create -n cobaya_env python`
`conda install -c conda-forge mpi4py`
`python -m pip install cobaya --upgrade`

All went well. Then I've moved on to installing the cosmological codes and data:

`cobaya-install cosmo -p /codes/cobaya_packages`

This is where the problem begins, apparently it no longer installs Planck `clik` likelihood code automatically. After looking it up, I've used:

`cobaya-install test.yaml --debug`

Leading to error
` [planck_2018_highl_plik.TTTEEE] *WARNING* clik code installation failed! Try configuring+compiling by hand at /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck`

I've compiled the code manually using:

`waf configure --lapack_install --cfitsio_install`

followed by:

`waf install`

and sourcing the profile as requested. All went well.
Finally, I ran `cobaya-install test.yaml --debug` again to make sure all went well, getting no errors:
`[install] All requested components' dependencies correctly installed at /gpfs0/elyk/users/talabadi/codes/cobaya_packages`

But when I initiate a run with the same `test.yaml` file I get an error
`AttributeError: module 'clik' has no attribute 'lkl'`

--------------------------------------------------------------------------------------------------------------
OUTPUT
=======

`cobaya-install test.yaml --debug`

...

================================================================================
likelihood:planck_2018_highl_plik.TTTEEE

================================================================================

 2023-04-05 15:56:21,743 [install] Checking if dependencies have already been installed...
 2023-04-05 15:56:21,743 [clik] Attempting import from /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck.
 2023-04-05 15:56:21,743 [clik] No (compiled) installation of 'clik' at /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck: [Errno 2] No such file or directory: '/gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck'
 2023-04-05 15:56:21,765 [planck_2018_lensing.native] The given installation path does not exist: '/gpfs0/elyk/users/talabadi/codes/cobaya_packages/data/planck_supp_data_and_covmats'
 2023-04-05 15:56:21,765 [install] Check found no existing installation
 2023-04-05 15:56:21,765 [install] Installing...
 2023-04-05 15:56:21,769 [clik] Attempting import from /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck.
 2023-04-05 15:56:21,770 [clik] No (compiled) installation of 'clik' at /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck: Could not find a clik installation under /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck
 2023-04-05 15:56:21,770 [planck_2018_highl_plik.TTTEEE] Installing the clik code.
 2023-04-05 15:56:21,770 [clik] Installing pre-requisites...
Requirement already satisfied: cython in /gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages (0.29.34)
Requirement already satisfied: astropy in /gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages (5.2.2)
Requirement already satisfied: numpy>=1.20 in /gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages (from astropy) (1.24.2)
Requirement already satisfied: pyerfa>=2.0 in /gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages (from astropy) (2.0.0.3)
Requirement already satisfied: PyYAML>=3.13 in /gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages (from astropy) (6.0)
Requirement already satisfied: packaging>=19.0 in /gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages (from astropy) (23.0)
 2023-04-05 15:56:23,287 [clik] Downloading...
 2023-04-05 15:56:23,290 [urllib3.connectionpool] Starting new HTTPS connection (1): github.com:443
 2023-04-05 15:56:23,698 [urllib3.connectionpool] https://github.com:443 "GET /benabed/clik/archive/refs/heads/main.zip HTTP/1.1" 302 0
 2023-04-05 15:56:23,701 [urllib3.connectionpool] Starting new HTTPS connection (1): codeload.github.com:443
 2023-04-05 15:56:24,092 [urllib3.connectionpool] https://codeload.github.com:443 "GET /benabed/clik/zip/refs/heads/main HTTP/1.1" 200 None
29.8MiB [00:08, 3.80MiB/s]
 2023-04-05 15:56:32,323 [clik] Downloaded filename clik-main.zip
 2023-04-05 15:56:32,324 [clik] Got: clik-main.zip
 2023-04-05 15:56:34,154 [clik] Decompressed: clik-main.zip
 2023-04-05 15:56:34,162 [clik] Installing from directory /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main
 2023-04-05 15:56:34,162 [clik] Configuring... (and maybe installing dependencies...)
Setting top to                           : /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main 
Setting out to                           : /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main/build 
get clik version                         : clik_16.0b1-2-g63c889f3aa9c 
Checking for program 'gcc, cc'           : /bin/gcc 
Checking for program 'ar'                : /bin/ar 
Check gcc version                        : 8.5.0 
Compile a test code with gcc             : yes 
Setting architecture flag to             : ['-m64'] 
Checking for program 'ifort'             : not found 
ifort not found, defaulting to gfortran (cause: 'Could not find the program ['ifort']
(complete log in /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main/build/config.log)') 
Checking for program 'gfortran, g77'     : /bin/gfortran 
Checking for program 'ar'                : /bin/ar 
Check gfortran version                   : GNU Fortran (GCC) 8.5.0 20210514 (Red Hat 8.5.0-16.0.2) 
Compile a test code with gfortran        : yes 
retrieve gfortran link line              : ok 
gfortran link line                       : -L/gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main -lgfortran -lgomp 
Setting install root to                  : /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main 
Setting install bin directory to         : /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main/bin 
Setting install lib directory to         : /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main/lib 
Setting install include directory to     : /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main/include 
Checking for program 'python'            : /gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/bin/python 
Checking for python version              : 3.11.2 
python-config                            : /gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/bin/python3.11-config 
Asking python-config for pyembed '--cflags --libs --ldflags --embed' flags : yes 
Testing pyembed configuration                                              : yes 
Checking for library dl                                                    : yes 
checking for RTLD_DEFAULT in dl                                            : no 
compile with debug option                                                  : OFF 
Checking for program 'pmc-config'                                          : not found 
Checking for library pmc                                                   : not found 
Checking for library ['lapack', 'blas']                                    : not found 
lapack not found 
check that lapack_prefix or lapack_lib and lapack_include command line options point toward your lapack install 
or check that lapack is compiled in 64 bit 
or install automatically using cmdline option --lapack_install 

The configuration failed
(complete log in /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main/build/config.log)

 2023-04-05 15:56:36,557 [clik] *ERROR* Configuration failed!
 2023-04-05 15:56:36,558 [planck_2018_highl_plik.TTTEEE] *WARNING* clik code installation failed! Try configuring+compiling by hand at /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck
 2023-04-05 15:56:36,590 [planck_2018_lensing.native] *ERROR* The given installation path does not exist: '/gpfs0/elyk/users/talabadi/codes/cobaya_packages/data/planck_supp_data_and_covmats'
 2023-04-05 15:56:36,591 [planck_2018_highl_plik.TTTEEE] Downloading the likelihood data.
 2023-04-05 15:56:36,611 [urllib3.connectionpool] Starting new HTTPS connection (1): pla.esac.esa.int:443
 2023-04-05 15:56:37,287 [urllib3.connectionpool] https://pla.esac.esa.int:443 "GET /pla-sl/data-action?COSMOLOGY.COSMOLOGY_OID=151902 HTTP/1.1" 200 None
57.5MiB [00:06, 9.09MiB/s]                                                                                                                                                              
 2023-04-05 15:56:43,923 [planck_2018_highl_plik.TTTEEE] Downloaded filename COM_Likelihood_Data-baseline_R3.00.tar.gz
 2023-04-05 15:56:43,924 [planck_2018_highl_plik.TTTEEE] Got: COM_Likelihood_Data-baseline_R3.00.tar.gz
 2023-04-05 15:56:44,629 [planck_2018_highl_plik.TTTEEE] Decompressed: COM_Likelihood_Data-baseline_R3.00.tar.gz
 2023-04-05 15:56:44,635 [planck_2018_lensing.native] *ERROR* The given installation path does not exist: '/gpfs0/elyk/users/talabadi/codes/cobaya_packages/data/planck_supp_data_and_covmats'
 2023-04-05 15:56:44,635 [planck_2018_lensing.native] Downloading CobayaSampler/planck_supp_data_and_covmats data...
 2023-04-05 15:56:44,636 [urllib3.connectionpool] Starting new HTTPS connection (1): github.com:443
 2023-04-05 15:56:45,095 [urllib3.connectionpool] https://github.com:443 "GET /CobayaSampler/planck_supp_data_and_covmats/archive/v2.01.tar.gz HTTP/1.1" 302 0
 2023-04-05 15:56:45,098 [urllib3.connectionpool] Starting new HTTPS connection (1): codeload.github.com:443
 2023-04-05 15:56:46,686 [urllib3.connectionpool] https://codeload.github.com:443 "GET /CobayaSampler/planck_supp_data_and_covmats/tar.gz/refs/tags/v2.01 HTTP/1.1" 200 None
6.34MiB [00:01, 4.49MiB/s]
 2023-04-05 15:56:48,171 [planck_2018_lensing.native] Downloaded filename planck_supp_data_and_covmats-2.01.tar.gz
 2023-04-05 15:56:48,172 [planck_2018_lensing.native] Got: planck_supp_data_and_covmats-2.01.tar.gz
 2023-04-05 15:56:52,054 [planck_2018_lensing.native] Decompressed: planck_supp_data_and_covmats-2.01.tar.gz
 2023-04-05 15:56:52,056 [planck_2018_lensing.native] planck_supp_data_and_covmats v2.01 downloaded and decompressed correctly.
 2023-04-05 15:56:52,057 [install] *ERROR* Installation failed! Look at the error messages above. Solve them and try again, or, if you are unable to solve them, install the packages required by this component manually.

================================================================================
likelihood:planck_2018_lensing.clik

================================================================================

 2023-04-05 15:56:52,057 [install] Checking if dependencies have already been installed...
 2023-04-05 15:56:52,057 [clik] Attempting import from /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck.
 2023-04-05 15:56:52,058 [clik] 'clik' to be imported from (sub)directory /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main/lib/python/site-packages
 2023-04-05 15:56:52,058 [clik] Could not import 'clik' from /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck: No module named 'clik'
 2023-04-05 15:56:52,061 [install] Check found no existing installation
 2023-04-05 15:56:52,061 [install] Installing...
 2023-04-05 15:56:52,061 [planck_2018_lensing.clik] Previous clik install failed, skipping
 2023-04-05 15:56:52,061 [install] *ERROR* Installation failed! Look at the error messages above. Solve them and try again, or, if you are unable to solve them, install the packages required by this component manually.
...

--------------------------------------------------------------------------------------------------------------
`cobaya-install test.yaml --debug`

 2023-04-05 16:22:19,631 [install] Installing external packages at '/gpfs0/elyk/users/talabadi/codes/cobaya_packages'
 2023-04-05 16:22:19,633 [install] The installation path has been written into the global config file: /gpfs0/elyk/users/talabadi/.config/cobaya/config.yaml

================================================================================
sampler:mcmc

================================================================================

 2023-04-05 16:22:19,636 [install] Checking if dependencies have already been installed...
 2023-04-05 16:22:19,636 [install] Component 'sampler:mcmc' is a fully built-in component: nothing to do.

================================================================================
theory:classy

================================================================================

 2023-04-05 16:22:19,640 [install] Checking if dependencies have already been installed...
 2023-04-05 16:22:19,640 [classy] Attempting import from /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/classy.
 2023-04-05 16:22:19,641 [classy] 'classy' to be imported from (sub)directory /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/classy/python/build/lib.linux-x86_64-cpython-311
 2023-04-05 16:22:19,643 [classy] `classy` module loaded successfully from /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/classy/python/build/lib.linux-x86_64-cpython-311
 2023-04-05 16:22:19,643 [install] External dependencies for this component already installed.
 2023-04-05 16:22:19,643 [install] Doing nothing.

================================================================================
likelihood:planck_2018_lowl.TT

================================================================================

 2023-04-05 16:22:19,650 [install] Checking if dependencies have already been installed...
 2023-04-05 16:22:19,651 [install] External dependencies for this component already installed.
 2023-04-05 16:22:19,651 [install] Doing nothing.

================================================================================
likelihood:planck_2018_lowl.EE

================================================================================

 2023-04-05 16:22:19,651 [install] Checking if dependencies have already been installed...
 2023-04-05 16:22:19,652 [install] External dependencies for this component already installed.
 2023-04-05 16:22:19,652 [install] Doing nothing.

================================================================================
likelihood:planck_2018_highl_plik.TTTEEE

================================================================================

 2023-04-05 16:22:19,653 [install] Checking if dependencies have already been installed...
 2023-04-05 16:22:19,653 [clik] Attempting import from /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck.
 2023-04-05 16:22:19,654 [clik] 'clik' to be imported from (sub)directory /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main/lib/python/site-packages
Cannot use clik wrapper (cause = '/usr/lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b')
Cannot use clik_lensing wrapper (cause = '/usr/lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b')
 2023-04-05 16:22:19,804 [clik] `clik` module loaded successfully from /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main/lib/python/site-packages/clik
 2023-04-05 16:22:19,828 [install] External dependencies for this component already installed.
 2023-04-05 16:22:19,828 [install] Doing nothing.

================================================================================
likelihood:planck_2018_lensing.clik

================================================================================

 2023-04-05 16:22:19,828 [install] Checking if dependencies have already been installed...
 2023-04-05 16:22:19,829 [clik] Attempting import from /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck.
 2023-04-05 16:22:19,829 [clik] 'clik' to be imported from (sub)directory /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main/lib/python/site-packages
Cannot use clik wrapper (cause = '/usr/lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b')
Cannot use clik_lensing wrapper (cause = '/usr/lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b')
 2023-04-05 16:22:19,837 [clik] `clik` module loaded successfully from /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main/lib/python/site-packages/clik
 2023-04-05 16:22:19,840 [install] External dependencies for this component already installed.
 2023-04-05 16:22:19,840 [install] Doing nothing.

================================================================================
likelihood:bao.sixdf_2011_bao

================================================================================

 2023-04-05 16:22:19,841 [install] Checking if dependencies have already been installed...
 2023-04-05 16:22:19,841 [install] External dependencies for this component already installed.
 2023-04-05 16:22:19,841 [install] Doing nothing.

================================================================================
likelihood:bao.sdss_dr7_mgs

================================================================================

 2023-04-05 16:22:19,842 [install] Checking if dependencies have already been installed...
 2023-04-05 16:22:19,842 [install] External dependencies for this component already installed.
 2023-04-05 16:22:19,842 [install] Doing nothing.

================================================================================
likelihood:bao.sdss_dr12_consensus_final

================================================================================

 2023-04-05 16:22:19,843 [install] Checking if dependencies have already been installed...
 2023-04-05 16:22:19,843 [install] External dependencies for this component already installed.
 2023-04-05 16:22:19,843 [install] Doing nothing.

================================================================================
likelihood:sn.pantheon

================================================================================

 2023-04-05 16:22:19,844 [install] Checking if dependencies have already been installed...
 2023-04-05 16:22:19,845 [install] External dependencies for this component already installed.
 2023-04-05 16:22:19,845 [install] Doing nothing.

================================================================================
likelihood:H0.riess201903

================================================================================

 2023-04-05 16:22:19,846 [install] Checking if dependencies have already been installed...
 2023-04-05 16:22:19,846 [install] Component 'likelihood:H0.riess201903' is a fully built-in component: nothing to do.

================================================================================
likelihood:des_y1.joint

================================================================================

 2023-04-05 16:22:19,847 [install] Checking if dependencies have already been installed...
 2023-04-05 16:22:19,847 [install] External dependencies for this component already installed.
 2023-04-05 16:22:19,847 [install] Doing nothing.

================================================================================
* Summary * 
* 
================================================================================

 2023-04-05 16:22:19,847 [install] All requested components' dependencies correctly installed at /gpfs0/elyk/users/talabadi/codes/cobaya_packages

--------------------------------------------------------------------------------------------------------------
`cobaya-run --test test.yaml`

[output] Output to be read-from/written-into folder '.', with prefix 'test'
[output] Found existing info files with the requested output prefix: 'test'
[prior] *WARNING* External prior 'SZ' loaded. Mind that it might not be normalized!
[classy] `classy` module loaded successfully from /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/classy/python/build/lib.linux-x86_64-cpython-311
Cannot use clik wrapper (cause = '/usr/lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b')
Cannot use clik_lensing wrapper (cause = '/usr/lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b')
[planck_2018_highl_plik.ttteee] `clik` module loaded successfully from /gpfs0/elyk/users/talabadi/codes/cobaya_packages/code/planck/clik-main/lib/python/site-packages/clik
[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 74, in initialize
    else clik.clik(self.clik_file)
         ^^^^^^^^^
AttributeError: module 'clik' has no attribute 'clik'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/bin/cobaya-run", line 8, in <module>
    sys.exit(run_script())
             ^^^^^^^^^^^^
  File "/gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages/cobaya/run.py", line 203, in run_script
    run(info, **arguments.__dict__)
  File "/gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages/cobaya/run.py", line 132, in run
    with Model(updated_info["params"], updated_info["likelihood"],
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages/cobaya/model.py", line 247, in __init__
    self.likelihood = LikelihoodCollection(info_likelihood, theory=self.theory,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages/cobaya/likelihood.py", line 255, in __init__
    self.add_instance(name, like_class(info, packages_path=packages_path,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages/cobaya/likelihood.py", line 89, in __init__
    super().__init__(info, name=name, timing=timing,
  File "/gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages/cobaya/theory.py", line 65, in __init__
    super().__init__(info, name=name, timing=timing,
  File "/gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages/cobaya/component.py", line 324, in __init__
    self.initialize()
  File "/gpfs0/elyk/users/talabadi/anaconda3/envs/cobaya_env/lib/python3.11/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 75, in initialize
    except clik.lkl.CError:
           ^^^^^^^^
AttributeError: module 'clik' has no attribute 'lkl'

-------------------------------------------------------------

**Comment by fmccarthy** [comment]
Hi, I also get this issue, I wonder  have you sorted out?

**Comment by cmbant** [comment]
The first error message says it can't find lapack. The second error says 
`Cannot use clik wrapper (cause = '/usr/lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b`
Probably some env/library compatibility issue. You can report clik install errors at https://github.com/benabed/clik - personally I'm fed up with clik not working for random reasons which are AFAIK nothing to do with Cobaya.

You can now run latest Planck NPIPE likelihoods without installing clik, as lowl TT, EE and high-L NPIPE Camspec and NPIPE lensing are all native python packages. You only need to install clik if you need to run original 2018 plik likelihoods.

**Comment by Xx-Luffy-xX** [comment]
Thanks, I will try them. I agree, every time I start a new environment for a project with `clik` I find myself in a new adventure of trying to make it work properly.

I also couldn't reproduce this error on my Mac, everything works fine there... But I need it to work on the HPC!

Thanks again,
Tal
