### ISSUE TITLE
pyactlike Compatibility

### ISSUE THREAD

**Issue by simrannerval** [CobayaSampler/cobaya#296]
Hello, 

I am trying to run the newest version of Cobaya with [pyactlike (ACT DR4)](https://github.com/ACTCollaboration/pyactlike). When using the same yaml file as the older version of Cobaya:

```
likelihood:
    pyactlike.ACTPol_lite_DR4:
      python_path: /home/simran/pyactlike
      components: 
            - tt
            - te
            - ee
      lmax: 6000

params:
    omegabh2: 0.02225
    omegach2: 0.1198
    H0: 67.3
    tau: 0.06
    As: 2.2e-9
    ns: 0.96
    yp2:
        prior:
            min: 0.5
            max: 1.5

sampler:
    mcmc:
        proposal_scale: 2.4

output: chains/actdr4_onlysampyp2_test
```

 I get the following error:

```
No protocol specified
[output] Output to be read-from/written-into folder 'chains', with prefix 'actdr4_onlysampyp2_test'
[model] *ERROR* Requirement Cl of pyactlike.ACTPol_lite_DR4 is not provided by any component, nor sampled directly
[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/home/simran/venv_cobaya/bin/cobaya-run", line 8, in <module>
    sys.exit(run_script())
  File "/home/simran/venv_cobaya/lib/python3.8/site-packages/cobaya/run.py", line 203, in run_script
    run(info, **arguments.__dict__)
  File "/home/simran/venv_cobaya/lib/python3.8/site-packages/cobaya/run.py", line 132, in run
    with Model(updated_info["params"], updated_info["likelihood"],
  File "/home/simran/venv_cobaya/lib/python3.8/site-packages/cobaya/model.py", line 254, in __init__
    self._set_dependencies_and_providers(skip_unused_theories=skip_unused_theories)
  File "/home/simran/venv_cobaya/lib/python3.8/site-packages/cobaya/model.py", line 763, in _set_dependencies_and_providers
    raise LoggedError(self.log,
cobaya.log.LoggedError: Requirement Cl of pyactlike.ACTPol_lite_DR4 is not provided by any component, nor sampled directly
-------------------------------------------------------------

```
Comparing the example of how to use an external likelihood class [here](https://cobaya.readthedocs.io/en/latest/cosmo_external_likelihood_class.html), it seems like the `get_requirements` functions follow the same format. Here is the `get_requirements` function from the cobaya example:

```
def get_requirements(self):
        """
         return dictionary specifying quantities calculated by a theory code are needed

         e.g. here we need C_L^{tt} to lmax=2500 and the H0 value
        """
        return {'Cl': {'tt': 2500}, 'H0': None}
```

and here is the `get_requirements` function from pyactlike:

```
def get_requirements(self):
        # State requisites to the theory code
        self.l_max = self.lmax
        return {"yp2": None, "Cl": {cl: self.l_max for cl in self.components}}

```

I was wondering if any guidance could please be given on how I can fix this issue and have pyactlike compatible with the newest version of cobaya? Thank you in advance!

**Comment by cmbant** [comment]
No theory block in your yaml?
