### ISSUE TITLE
MCMC' object has no attribute '_prior_tries_warning

### ISSUE THREAD

**Issue by eatdust** [CobayaSampler/cobaya#297]
Hi there,
in a long and painful process of debugging MPI runs with Cobaya, I met this error.

Best,
Chris.

```shell

[2 : exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/usr/bin/cobaya-run", line 33, in <module>
    sys.exit(load_entry_point('cobaya==3.3.1', 'console_scripts', 'cobaya-run')())
  File "/usr/lib/python3.10/site-packages/cobaya/run.py", line 203, in run_script
    run(info, **arguments.__dict__)
  File "/usr/lib/python3.10/site-packages/cobaya/run.py", line 155, in run
    sampler.run()
  File "/usr/lib/python3.10/site-packages/cobaya/samplers/mcmc/mcmc.py", line 364, in run
    self.get_new_sample()
  File "/usr/lib/python3.10/site-packages/cobaya/samplers/mcmc/mcmc.py", line 443, in get_new_sample_metropolis
    self.process_accept_or_reject(accept, trial, trial_results)
  File "/usr/lib/python3.10/site-packages/cobaya/samplers/mcmc/mcmc.py", line 604, in process_accept_or_reject
    not getattr(self, '_prior_tries_warning'):
AttributeError: 'MCMC' object has no attribute '_prior_tries_warning'
-------------------------------------------------------------

[3 : exception handler] [3: mcmc] Another process failed - exiting.
[3 : exception handler] ---------------------------------------

```

**Comment by cmbant** [comment]
https://github.com/CobayaSampler/cobaya/commit/c23596564539f57289703eeb6d284df73a0271ec
