### ISSUE TITLE
Attribute Error in MCMC sampling

### ISSUE THREAD

**Issue by nehapjoshi** [CobayaSampler/cobaya#307]
I'm running cobaya with CAMB and using the MCMC sampler with a finite number of max_tries.  The MCMC runs for a bit before crashing and spitting out this error:

> Traceback (most recent call last):
  File "/home3/nehajo/.local/bin/cobaya-run", line 8, in <module>
    sys.exit(run_script())
  File "/home3/nehajo/.local/lib/python3.10/site-packages/cobaya/run.py", line 203, in run_script
    run(info, **arguments.__dict__)
  File "/home3/nehajo/.local/lib/python3.10/site-packages/cobaya/run.py", line 155, in run
    sampler.run()
  File "/home3/nehajo/.local/lib/python3.10/site-packages/cobaya/samplers/mcmc/mcmc.py", line 364, in run
    self.get_new_sample()
  File "/home3/nehajo/.local/lib/python3.10/site-packages/cobaya/samplers/mcmc/mcmc.py", line 443, in get_new_sample_metropolis
    self.process_accept_or_reject(accept, trial, trial_results)
  File "/home3/nehajo/.local/lib/python3.10/site-packages/cobaya/samplers/mcmc/mcmc.py", line 604, in process_accept_or_reject
    not getattr(self, '_prior_tries_warning'):
AttributeError: 'MCMC' object has no attribute '_prior_tries_warning'

I haven't found a way to avoid this with my likelihood.

**Comment by cmbant** [comment]
Make sure you have the latest version?

**Comment by nehapjoshi** [comment]
When I try to update through pip, it treats it like it's updated.  When I check the version it is 3.3.1.

**Comment by cmbant** [comment]
pypi should have 3.3.2. If neccessary try making a new clean env?

**Comment by nehapjoshi** [comment]
I think that's the issue, thank you!
