### ISSUE TITLE
cobaya-install planck_2018_highl_plik.TTTEEE fails 

### ISSUE THREAD

**Issue by MarcosArize** [CobayaSampler/cobaya#359]
Hi all,

when im try to install  planck_2018_highl_plik.TTTEEE gives me this error 

`Traceback (most recent call last):
  File "/usr/local/bin/cobaya-install", line 8, in <module>
    sys.exit(install_script())
  File "/usr/local/lib/python3.10/dist-packages/cobaya/install.py", line 637, in install_script
    install(*infos, path=getattr(arguments, packages_path_arg), logger=logger,
  File "/usr/local/lib/python3.10/dist-packages/cobaya/install.py", line 262, in install
    has_been_installed = is_installed(
  File "/usr/local/lib/python3.10/dist-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 162, in is_installed
    result &= bool(is_installed_clik(
  File "/usr/local/lib/python3.10/dist-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 311, in is_installed_clik
    return bool(load_clik(
  File "/usr/local/lib/python3.10/dist-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 300, in load_clik
    clik = load_external_module(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/cobaya/component.py", line 818, in load_external_module
    module = _bare_load_external_module(not_installed_level="debug", **load_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/cobaya/component.py", line 741, in _bare_load_external_module
    import_path = get_import_path(path)
  File "/usr/local/lib/python3.10/dist-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 283, in get_clik_import_path
    installed_version = version.parse(f.readline().split("_")[-1].split('-')[0])
  File "/usr/local/lib/python3.10/dist-packages/packaging/version.py", line 54, in parse
    return Version(version)
  File "/usr/local/lib/python3.10/dist-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'ae99bcea1cd9
'`

someone knows how to solve it?

**Comment by cmbant** [comment]
I assume this is using latest cobaya? do you know where the "ae99bcea1cd9" value is coming from? It should be downloading https://github.com/benabed/clik/archive/refs/heads/main.zip and looking in the svnversion file, which should work.. 

You can of course also use the NPIPE planck likelihoods which are pure python.

**Comment by cmbant** [comment]
Please try the latest master on github, I think I fixed this by getting the version a different way.
