### ISSUE TITLE
*ERROR* Requested fast/slow separation, but all parameters have the same speed

### ISSUE THREAD

**Issue by ark93-cosmo** [CobayaSampler/cobaya#365]
Hi,
I'm doing a test run of LCDM with BAO data only (DESI+SDSS+6dFGS, as per the DESI [paper](https://arxiv.org/abs/2404.03002) description) with CLASS and with CAMB. If I run with CAMB it goes well, while if I run with CLASS I get the error in the title. I can get rid of the error by setting `'drag': False` in the sampler dictionary, but I don't understand why this is happening. 
The python script I used to run the chains:
```
import numpy as np

import matplotlib.pyplot as plt
import sys

import warnings
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings(action='ignore', category=DataConversionWarning)
from sklearn.exceptions import ConvergenceWarning
warnings.filterwarnings(action='ignore', category=ConvergenceWarning)

from cobaya.run import run

import cobaya

info={  'force': True,
        'resume': False,
        #'debug': True,
        'timing': True,
        'output': '/data83/NEUCosmos/khalife/IDM/Lin_vs_None/LCDM/BAO_Non-linear/CLASS',
        'theory': {
            'classy': {
                'extra_args': {
                    'N_ncdm': 1,
                    'N_ur': 0.00441,
                    'deg_ncdm': 3,
                    'm_ncdm': 0.02,
                    'non linear': 'halofit',
                    'output': 'mPk'
                    #'nonlinear_min_k_max': 20
                    },
                'path': '/data83/NEUCosmos/khalife/Codes/code/classy/',
                'ignore_obsolete': True
            }
        },
        'likelihood': {'bao.sixdf_2011_bao':{},
                        'bao.sdss_dr7_mgs':{},
                        'bao.sdss_dr12_lrg_bao_dmdh':{},
                        'bao.desi_2024_bao_lrg_z2':{},
                        'bao.desi_2024_bao_lrgpluselg_z1':{},
                        'bao.desi_2024_bao_elg_z2':{},
                        'bao.desi_2024_bao_qso_z1':{},
                        'bao.desi_2024_eboss_bao_lya':{}
        },
        "sampler": {
          "mcmc": {
             "Rminus1_cl_stop": 0.23,
             "Rminus1_stop": 0.01,
            # "drag": True,
             "covmat": "/data83/NEUCosmos/khalife/LCDM_BAO.covmat",
             "measure_speeds": True,
             "oversample_power": 0.4,
             "output_every": 1,
             "proposal_scale": 1.9
              }
         },
        "params": {
                    'logA': {'drop': True,
                        'latex': '\\log(10^{10} A_\\mathrm{s})',
                        'prior': {'max': 3.91, 'min': 1.61},
                        'proposal': 0.005,
                        'ref': {'dist': 'norm', 'loc': 3.05, 'scale': 0.01}
                    },
                    'n_s': {'latex': 'n_\\mathrm{s}',
                        'prior': {'max': 1.2, 'min': 0.8},
                        'proposal': 0.002,
                        'ref': {'dist': 'norm', 'loc': 0.965, 'scale': 0.004},
                        'renames': ['ns']
                    },
                    'omega_b': {'latex': '\\Omega_\\mathrm{b} h^2',
                        'prior': {'max': 0.1, 'min': 0.005},
                        'proposal': 0.0001,
                        'ref': {'dist': 'norm','loc': 0.0224,'scale': 0.0001},
                        'renames': ['omegabh2']
                    },
                    'omega_cdm': {'latex': '\\Omega_\\mathrm{c} h^2',
                          'prior': {'max': 0.99, 'min': 0.001},
                          'proposal': 0.0005,
                          'ref': {'dist': 'norm',
                                  'loc': 0.12,
                                  'scale': 0.001},
                          'renames': ['omegach2']
                    },
                   "theta_s_1e2": { "prior": { "max": 10, "min": 0.5},
                                    "proposal": 0.002,
                                    "drop": True,
                                    "ref": 1.041400294,
                                    "latex": "100\\theta_\\mathrm{s}"
                   },
                    "100*theta_s": {"latex": "100\\theta_*", 
                                   "derived": False,
                                   "value": "lambda theta_s_1e2: theta_s_1e2"
                                  },
                    'tau_reio': {'latex': '\\tau_\\mathrm{reio}',
                        'prior': {'dist':'norm','loc':0.054,'scale':0.0074},
                         'proposal': 0.003,
                         'ref': {'dist': 'norm',
                                 'loc': 0.055,
                                 'scale': 0.006},
                         'renames': ['tau']
                  },
            'A': {'derived': 'lambda A_s: 1e9*A_s',
                  'latex': '10^9 A_\\mathrm{s}'
                  },
            'A_s': {'derived': True,
                    'latex': 'A_\\mathrm{s}',
                    'renames': ['As'],
                    'value': 'lambda logA: 1e-10*np.exp(logA)'},
            'H0': {'latex': 'H_0',
                   'derived': True 
                },
            'Omega_Lambda': {'derived': True,
                             'latex': '\\Omega_\\Lambda',
                             'renames': ['omegal']},
            'Omega_m': {'derived': True,
                        'latex': '\\Omega_\\mathrm{m}',
                        'renames': ['omegam']},
            'YHe': {'derived': True,
                    'latex': 'Y_\\mathrm{P}',
                    'renames': ['yheused', 'yhe']},
            'age': {'derived': True, 'latex': '{\\rm{Age}}/\\mathrm{Gyr}'},
            'clamp': {'derived': 'lambda A_s, tau_reio: 1e9*A_s*np.exp(-2*tau_reio)',
                      'latex': '10^9 A_\\mathrm{s} e^{-2\\tau}'},
            'omegamh2': {'derived': 'lambda Omega_m, H0: Omega_m*(H0/100)**2',
                         'latex': '\\Omega_\\mathrm{m} h^2'},
            'rs_drag': {'derived': True,
                        'latex': 'r_\\mathrm{drag}',
                        'renames': ['rdrag']},
            's8h5': {'derived': 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)',
                     'latex': '\\sigma_8/h^{0.5}'},
            's8omegamp25': {'derived': 'lambda sigma8, Omega_m: sigma8*Omega_m**0.25',
                            'latex': '\\sigma_8 \\Omega_\\mathrm{m}^{0.25}'},
            's8omegamp5': {'derived': 'lambda sigma8, Omega_m: sigma8*Omega_m**0.5',
                           'latex': '\\sigma_8 \\Omega_\\mathrm{m}^{0.5}'},
            'sigma8': {'derived': True, 'latex': '\\sigma_8'},
            'z_reio': {'derived': True,
                       'latex': 'z_\\mathrm{re}',
                       'renames': ['zrei']},
            'chi2__BAO': {'derived': True, 'latex': '\\chi^2_\\mathrm{BAO}'}
            }
}

updated_info, sampler = run(info)
```
The resulting log:
```
[0 : output] Output to be read-from/written-into folder '/data83/NEUCosmos/khalife/LCDM/BAO_ERROR', with prefix 'CLASS'
[0 : classy] `classy` module loaded successfully from /automnt/data83/NEUCosmos/khalife/Codes/code/classy/python/build/lib.linux-x86_64-cpython-39
[4 : bao.sixdf_2011_bao] Initialized.
[0 : bao.sixdf_2011_bao] Initialized.
[1 : bao.sixdf_2011_bao] Initialized.
[2 : bao.sixdf_2011_bao] Initialized.
[5 : bao.sixdf_2011_bao] Initialized.
[3 : bao.sixdf_2011_bao] Initialized.
[4 : bao.sdss_dr12_lrg_bao_dmdh] Initialized.
[5 : bao.sdss_dr12_lrg_bao_dmdh] Initialized.
[0 : bao.sdss_dr12_lrg_bao_dmdh] Initialized.
[1 : bao.sdss_dr12_lrg_bao_dmdh] Initialized.
[2 : bao.sdss_dr12_lrg_bao_dmdh] Initialized.
[3 : bao.sdss_dr12_lrg_bao_dmdh] Initialized.
[2 : bao.desi_2024_bao_lrg_z2] Initialized.
[4 : bao.desi_2024_bao_lrg_z2] Initialized.
[3 : bao.desi_2024_bao_lrg_z2] Initialized.
[5 : bao.desi_2024_bao_lrg_z2] Initialized.
[1 : bao.desi_2024_bao_lrg_z2] Initialized.
[0 : bao.desi_2024_bao_lrg_z2] Initialized.
[3 : bao.desi_2024_bao_lrgpluselg_z1] Initialized.
[4 : bao.desi_2024_bao_lrgpluselg_z1] Initialized.
[1 : bao.desi_2024_bao_lrgpluselg_z1] Initialized.
[5 : bao.desi_2024_bao_lrgpluselg_z1] Initialized.
[2 : bao.desi_2024_bao_lrgpluselg_z1] Initialized.
[0 : bao.desi_2024_bao_lrgpluselg_z1] Initialized.
[1 : bao.desi_2024_bao_elg_z2] Initialized.
[4 : bao.desi_2024_bao_elg_z2] Initialized.
[5 : bao.desi_2024_bao_elg_z2] Initialized.
[0 : bao.desi_2024_bao_elg_z2] Initialized.
[2 : bao.desi_2024_bao_elg_z2] Initialized.
[3 : bao.desi_2024_bao_elg_z2] Initialized.
[1 : bao.desi_2024_bao_qso_z1] Initialized.
[3 : bao.desi_2024_bao_qso_z1] Initialized.
[4 : bao.desi_2024_bao_qso_z1] Initialized.
[5 : bao.desi_2024_bao_qso_z1] Initialized.
[0 : bao.desi_2024_bao_qso_z1] Initialized.
[2 : bao.desi_2024_bao_qso_z1] Initialized.
[1 : bao.desi_2024_eboss_bao_lya] Initialized.
[4 : bao.desi_2024_eboss_bao_lya] Initialized.
[0 : bao.desi_2024_eboss_bao_lya] Initialized.
[5 : bao.desi_2024_eboss_bao_lya] Initialized.
[2 : bao.desi_2024_eboss_bao_lya] Initialized.
[3 : bao.desi_2024_eboss_bao_lya] Initialized.
[0 : mcmc] Getting initial point... (this may take a few seconds)
[1 : mcmc] Getting initial point... (this may take a few seconds)
[2 : mcmc] Getting initial point... (this may take a few seconds)
[4 : mcmc] Getting initial point... (this may take a few seconds)
[5 : mcmc] Getting initial point... (this may take a few seconds)
[3 : mcmc] Getting initial point... (this may take a few seconds)
[1 : mcmc] Initial point: logA:3.018826, n_s:0.9629651, omega_b:0.02232417, omega_cdm:0.1185123, theta_s_1e2:1.042446, tau_reio:0.04125585
[2 : mcmc] Initial point: logA:2.997678, n_s:0.9771304, omega_b:0.0222193, omega_cdm:0.1175138, theta_s_1e2:1.042111, tau_reio:0.04837044
[4 : mcmc] Initial point: logA:2.994157, n_s:0.9694596, omega_b:0.02249647, omega_cdm:0.1177218, theta_s_1e2:1.042195, tau_reio:0.05627319
[3 : mcmc] Initial point: logA:3.003407, n_s:0.9634536, omega_b:0.02239421, omega_cdm:0.1180262, theta_s_1e2:1.041695, tau_reio:0.05412312
[5 : mcmc] Initial point: logA:2.984245, n_s:0.9650588, omega_b:0.02220396, omega_cdm:0.1188264, theta_s_1e2:1.041515, tau_reio:0.05456585
[0 : mcmc] Initial point: logA:2.988387, n_s:0.974424, omega_b:0.02224926, omega_cdm:0.1200308, theta_s_1e2:1.041876, tau_reio:0.05056187
[0 : model] Measuring speeds... (this may take a few seconds)
[0 : model] Setting measured speeds (per sec): {bao.sixdf_2011_bao: 2430.0, bao.sdss_dr7_mgs: 5400.0, bao.sdss_dr12_lrg_bao_dmdh: 3400.0, bao.desi_2024_bao_lrg_z2: 6220.0, bao.desi_2024_bao_lrgpluselg_z1: 6340.0, bao.desi_2024_bao_elg_z2: 6340.0, bao.desi_2024_bao_qso_z1: 6570.0, bao.desi_2024_eboss_bao_lya: 6400.0, classy: 1.27}
[4 : model] *ERROR* Requested fast/slow separation, but all parameters have the same speed.
[1 : model] *ERROR* Requested fast/slow separation, but all parameters have the same speed.
[2 : model] *ERROR* Requested fast/slow separation, but all parameters have the same speed.
[3 : model] *ERROR* Requested fast/slow separation, but all parameters have the same speed.
[4 : bao.sixdf_2011_bao] Average evaluation time for bao.sixdf_2011_bao: 0.000390897 s  (1 evaluations)
[1 : bao.sixdf_2011_bao] Average evaluation time for bao.sixdf_2011_bao: 0.000398642 s  (1 evaluations)
[2 : bao.sixdf_2011_bao] Average evaluation time for bao.sixdf_2011_bao: 0.000396277 s  (1 evaluations)
[3 : bao.sixdf_2011_bao] Average evaluation time for bao.sixdf_2011_bao: 0.000388262 s  (1 evaluations)
[4 : bao.sdss_dr7_mgs] Average evaluation time for bao.sdss_dr7_mgs: 0.000191832 s  (1 evaluations)
[5 : model] *ERROR* Requested fast/slow separation, but all parameters have the same speed.
[1 : bao.sdss_dr7_mgs] Average evaluation time for bao.sdss_dr7_mgs: 0.000181342 s  (1 evaluations)
[2 : bao.sdss_dr7_mgs] Average evaluation time for bao.sdss_dr7_mgs: 0.00018009 s  (1 evaluations)
[3 : bao.sdss_dr7_mgs] Average evaluation time for bao.sdss_dr7_mgs: 0.000182985 s  (1 evaluations)
[4 : bao.sdss_dr12_lrg_bao_dmdh] Average evaluation time for bao.sdss_dr12_lrg_bao_dmdh: 0.000288784 s  (1 evaluations)
[1 : bao.sdss_dr12_lrg_bao_dmdh] Average evaluation time for bao.sdss_dr12_lrg_bao_dmdh: 0.000283264 s  (1 evaluations)
[2 : bao.sdss_dr12_lrg_bao_dmdh] Average evaluation time for bao.sdss_dr12_lrg_bao_dmdh: 0.000288433 s  (1 evaluations)
[3 : bao.sdss_dr12_lrg_bao_dmdh] Average evaluation time for bao.sdss_dr12_lrg_bao_dmdh: 0.000299605 s  (1 evaluations)
[4 : bao.desi_2024_bao_lrg_z2] Average evaluation time for bao.desi_2024_bao_lrg_z2: 0.000157547 s  (1 evaluations)
[5 : bao.sixdf_2011_bao] Average evaluation time for bao.sixdf_2011_bao: 0.000478583 s  (1 evaluations)
[0 : model] *ERROR* Requested fast/slow separation, but all parameters have the same speed.
[3 : bao.desi_2024_bao_lrg_z2] Average evaluation time for bao.desi_2024_bao_lrg_z2: 0.000159901 s  (1 evaluations)
[4 : bao.desi_2024_bao_lrgpluselg_z1] Average evaluation time for bao.desi_2024_bao_lrgpluselg_z1: 0.000155975 s  (1 evaluations)
[1 : bao.desi_2024_bao_lrg_z2] Average evaluation time for bao.desi_2024_bao_lrg_z2: 0.000158429 s  (1 evaluations)
[2 : bao.desi_2024_bao_lrg_z2] Average evaluation time for bao.desi_2024_bao_lrg_z2: 0.000155433 s  (1 evaluations)
[5 : bao.sdss_dr7_mgs] Average evaluation time for bao.sdss_dr7_mgs: 0.000188735 s  (1 evaluations)
[0 : bao.sixdf_2011_bao] Average evaluation time for bao.sixdf_2011_bao: 0.000419642 s  (1 evaluations)
[1 : bao.desi_2024_bao_lrgpluselg_z1] Average evaluation time for bao.desi_2024_bao_lrgpluselg_z1: 0.000155543 s  (1 evaluations)
[2 : bao.desi_2024_bao_lrgpluselg_z1] Average evaluation time for bao.desi_2024_bao_lrgpluselg_z1: 0.000152978 s  (1 evaluations)
[3 : bao.desi_2024_bao_lrgpluselg_z1] Average evaluation time for bao.desi_2024_bao_lrgpluselg_z1: 0.000158329 s  (1 evaluations)
[4 : bao.desi_2024_bao_elg_z2] Average evaluation time for bao.desi_2024_bao_elg_z2: 0.000153689 s  (1 evaluations)
[5 : bao.sdss_dr12_lrg_bao_dmdh] Average evaluation time for bao.sdss_dr12_lrg_bao_dmdh: 0.000311117 s  (1 evaluations)
[3 : bao.desi_2024_bao_elg_z2] Average evaluation time for bao.desi_2024_bao_elg_z2: 0.000158028 s  (1 evaluations)
[1 : bao.desi_2024_bao_elg_z2] Average evaluation time for bao.desi_2024_bao_elg_z2: 0.000163498 s  (1 evaluations)
[2 : bao.desi_2024_bao_elg_z2] Average evaluation time for bao.desi_2024_bao_elg_z2: 0.000151726 s  (1 evaluations)
[4 : bao.desi_2024_bao_qso_z1] Average evaluation time for bao.desi_2024_bao_qso_z1: 0.000155183 s  (1 evaluations)
[0 : bao.sdss_dr7_mgs] Average evaluation time for bao.sdss_dr7_mgs: 0.00018561 s  (1 evaluations)
[5 : bao.desi_2024_bao_lrg_z2] Average evaluation time for bao.desi_2024_bao_lrg_z2: 0.000165983 s  (1 evaluations)
[3 : bao.desi_2024_bao_qso_z1] Average evaluation time for bao.desi_2024_bao_qso_z1: 0.000152528 s  (1 evaluations)
[1 : bao.desi_2024_bao_qso_z1] Average evaluation time for bao.desi_2024_bao_qso_z1: 0.000150013 s  (1 evaluations)
[4 : bao.desi_2024_eboss_bao_lya] Average evaluation time for bao.desi_2024_eboss_bao_lya: 0.000152677 s  (1 evaluations)
[2 : bao.desi_2024_bao_qso_z1] Average evaluation time for bao.desi_2024_bao_qso_z1: 0.000149221 s  (1 evaluations)
[0 : bao.sdss_dr12_lrg_bao_dmdh] Average evaluation time for bao.sdss_dr12_lrg_bao_dmdh: 0.000293894 s  (1 evaluations)
[5 : bao.desi_2024_bao_lrgpluselg_z1] Average evaluation time for bao.desi_2024_bao_lrgpluselg_z1: 0.00016419 s  (1 evaluations)
[3 : bao.desi_2024_eboss_bao_lya] Average evaluation time for bao.desi_2024_eboss_bao_lya: 0.000156065 s  (1 evaluations)
[1 : bao.desi_2024_eboss_bao_lya] Average evaluation time for bao.desi_2024_eboss_bao_lya: 0.000151947 s  (1 evaluations)
[2 : bao.desi_2024_eboss_bao_lya] Average evaluation time for bao.desi_2024_eboss_bao_lya: 0.000162717 s  (1 evaluations)
[0 : bao.desi_2024_bao_lrg_z2] Average evaluation time for bao.desi_2024_bao_lrg_z2: 0.000167045 s  (1 evaluations)
[4 : classy] Average evaluation time for classy: 0.82519 s  (1 evaluations)
[5 : bao.desi_2024_bao_elg_z2] Average evaluation time for bao.desi_2024_bao_elg_z2: 0.000160142 s  (1 evaluations)
[3 : classy] Average evaluation time for classy: 0.800783 s  (1 evaluations)
[0 : bao.desi_2024_bao_lrgpluselg_z1] Average evaluation time for bao.desi_2024_bao_lrgpluselg_z1: 0.000158419 s  (1 evaluations)
[1 : classy] Average evaluation time for classy: 0.774214 s  (1 evaluations)
[2 : classy] Average evaluation time for classy: 0.78597 s  (1 evaluations)
[5 : bao.desi_2024_bao_qso_z1] Average evaluation time for bao.desi_2024_bao_qso_z1: 0.000154892 s  (1 evaluations)
[0 : bao.desi_2024_bao_elg_z2] Average evaluation time for bao.desi_2024_bao_elg_z2: 0.00015913 s  (1 evaluations)
[5 : bao.desi_2024_eboss_bao_lya] Average evaluation time for bao.desi_2024_eboss_bao_lya: 0.000158879 s  (1 evaluations)
[0 : bao.desi_2024_bao_qso_z1] Average evaluation time for bao.desi_2024_bao_qso_z1: 0.000151356 s  (1 evaluations)
[5 : classy] Average evaluation time for classy: 0.771599 s  (1 evaluations)
[0 : bao.desi_2024_eboss_bao_lya] Average evaluation time for bao.desi_2024_eboss_bao_lya: 0.000154902 s  (1 evaluations)
[0 : classy] Average evaluation time for classy: 0.7726 s  (1 evaluations)
[3 : exception handler] *ERROR* Requested fast/slow separation, but all parameters have the same speed.
[1 : exception handler] *ERROR* Requested fast/slow separation, but all parameters have the same speed.
[5 : exception handler] *ERROR* Requested fast/slow separation, but all parameters have the same speed.
[0 : exception handler] *ERROR* Requested fast/slow separation, but all parameters have the same speed.
[3 : exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/data83/NEUCosmos/khalife/LCDM/BAO.py", line 152, in <module>
    updated_info, sampler = run(info)
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/run.py", line 129, in run
    sampler = sampler_class(updated_info["sampler"][sampler_name],
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/sampler.py", line 279, in __init__
    self.initialize()
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/samplers/mcmc/mcmc.py", line 190, in initialize
    self.set_proposer_blocking()
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/samplers/mcmc/mcmc.py", line 273, in set_proposer_blocking
    self.model.get_param_blocking_for_sampler(
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/model.py", line 1157, in get_param_blocking_for_sampler
    raise LoggedError(self.log, "Requested fast/slow separation, "
cobaya.log.LoggedError: Requested fast/slow separation, but all parameters have the same speed.
-------------------------------------------------------------

[1 : exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/data83/NEUCosmos/khalife/LCDM/BAO.py", line 152, in <module>
    updated_info, sampler = run(info)
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/run.py", line 129, in run
    sampler = sampler_class(updated_info["sampler"][sampler_name],
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/sampler.py", line 279, in __init__
    self.initialize()
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/samplers/mcmc/mcmc.py", line 190, in initialize
    self.set_proposer_blocking()
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/samplers/mcmc/mcmc.py", line 273, in set_proposer_blocking
    self.model.get_param_blocking_for_sampler(
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/model.py", line 1157, in get_param_blocking_for_sampler
    raise LoggedError(self.log, "Requested fast/slow separation, "
cobaya.log.LoggedError: Requested fast/slow separation, but all parameters have the same speed.
-------------------------------------------------------------

[5 : exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/data83/NEUCosmos/khalife/LCDM/BAO.py", line 152, in <module>
    updated_info, sampler = run(info)
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/run.py", line 129, in run
    sampler = sampler_class(updated_info["sampler"][sampler_name],
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/sampler.py", line 279, in __init__
    self.initialize()
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/samplers/mcmc/mcmc.py", line 190, in initialize
    self.set_proposer_blocking()
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/samplers/mcmc/mcmc.py", line 273, in set_proposer_blocking
    self.model.get_param_blocking_for_sampler(
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/model.py", line 1157, in get_param_blocking_for_sampler
    raise LoggedError(self.log, "Requested fast/slow separation, "
cobaya.log.LoggedError: Requested fast/slow separation, but all parameters have the same speed.
-------------------------------------------------------------

[0 : exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/data83/NEUCosmos/khalife/LCDM/BAO.py", line 152, in <module>
    updated_info, sampler = run(info)
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/run.py", line 129, in run
    sampler = sampler_class(updated_info["sampler"][sampler_name],
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/sampler.py", line 279, in __init__
    self.initialize()
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/samplers/mcmc/mcmc.py", line 190, in initialize
    self.set_proposer_blocking()
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/samplers/mcmc/mcmc.py", line 273, in set_proposer_blocking
    self.model.get_param_blocking_for_sampler(
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/model.py", line 1157, in get_param_blocking_for_sampler
    raise LoggedError(self.log, "Requested fast/slow separation, "
cobaya.log.LoggedError: Requested fast/slow separation, but all parameters have the same speed.
-------------------------------------------------------------

[4 : exception handler] *ERROR* Requested fast/slow separation, but all parameters have the same speed.
[2 : exception handler] *ERROR* Requested fast/slow separation, but all parameters have the same speed.
[4 : exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/data83/NEUCosmos/khalife/LCDM/BAO.py", line 152, in <module>
    updated_info, sampler = run(info)
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/run.py", line 129, in run
    sampler = sampler_class(updated_info["sampler"][sampler_name],
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/sampler.py", line 279, in __init__
    self.initialize()
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/samplers/mcmc/mcmc.py", line 190, in initialize
    self.set_proposer_blocking()
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/samplers/mcmc/mcmc.py", line 273, in set_proposer_blocking
    self.model.get_param_blocking_for_sampler(
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/model.py", line 1157, in get_param_blocking_for_sampler
    raise LoggedError(self.log, "Requested fast/slow separation, "
cobaya.log.LoggedError: Requested fast/slow separation, but all parameters have the same speed.
-------------------------------------------------------------

[2 : exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/data83/NEUCosmos/khalife/LCDM/BAO.py", line 152, in <module>
    updated_info, sampler = run(info)
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/run.py", line 129, in run
    sampler = sampler_class(updated_info["sampler"][sampler_name],
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/sampler.py", line 279, in __init__
    self.initialize()
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/samplers/mcmc/mcmc.py", line 190, in initialize
    self.set_proposer_blocking()
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/samplers/mcmc/mcmc.py", line 273, in set_proposer_blocking
    self.model.get_param_blocking_for_sampler(
  File "/data83/NEUCosmos/khalife/cobaya/cobaya/model.py", line 1157, in get_param_blocking_for_sampler
    raise LoggedError(self.log, "Requested fast/slow separation, "
cobaya.log.LoggedError: Requested fast/slow separation, but all parameters have the same speed.
-------------------------------------------------------------

```
I fear turning drag off would slow down the runs.

Thanks in advance for the help!

**Comment by cmbant** [comment]
I don't think CLASS optimizes for initial power vs transfer function speeds, so all calls are the same speed. CAMB does (though the speed difference is not enough to use dragging - which I assume it doesn't actually use even with the option set due to the only-modest speed hierarchy).

**Comment by ark93-cosmo** [comment]
Thanks Antony!
I always used CLASS with `'drag': True`, and never got this error. But, it's the first time I use it with BAO data only. Usually it's a mix with CMB data. Could the optimization change with the type of data used?

**Comment by cmbant** [comment]
Yes if you include data that has fast nuisance parameters.
