### ISSUE TITLE
module 'clik' has no attribute 'lkl'

### ISSUE THREAD

**Issue by FereshtehMajidi** [CobayaSampler/cobaya#370]
Hi,

I have a problem installing the Cobaya packages. When I install them as it's been said on the website, it seems they are all there and installed successfully. But as soon as I run the "basic_cosmo.yaml" in "docs" file, I get these errors:

$ cobaya-run basic_classy.yaml 
[output] Output to be read-from/written-into folder '.', with prefix 'basic_classy'
[output] Found existing info files with the requested output prefix: 'basic_classy'
[prior] *WARNING* External prior 'SZ' loaded. Mind that it might not be normalized!
[classy] `classy` module loaded successfully from /arc/home/Fmajidi/Cobaya/cobaya-master/cobaya/code/classy/python/build/lib.linux-x86_64-cpython-311
Cannot use clik wrapper (cause = 'No module named 'clik.lkl'')
Cannot use clik_lensing wrapper (cause = 'No module named 'clik.lkl_lensing'')
[planck_2018_highl_plik.ttteee] `clik` module loaded successfully from /arc/home/Fmajidi/Cobaya/cobaya-master/cobaya/code/planck/clik-main/lib/python/site-packages/clik
[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/arc/home/Fmajidi/.local/lib/python3.11/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 75, in initialize
    else clik.clik(self.clik_file)
         ^^^^^^^^^
AttributeError: module 'clik' has no attribute 'clik'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/cobaya-run", line 8, in <module>
    sys.exit(run_script())
             ^^^^^^^^^^^^
  File "/arc/home/Fmajidi/.local/lib/python3.11/site-packages/cobaya/run.py", line 191, in run_script
    run(info, **arguments.__dict__)
  File "/arc/home/Fmajidi/.local/lib/python3.11/site-packages/cobaya/run.py", line 120, in run
    with Model(updated_info["params"], updated_info["likelihood"],
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/arc/home/Fmajidi/.local/lib/python3.11/site-packages/cobaya/model.py", line 247, in __init__
    self.likelihood = LikelihoodCollection(info_likelihood, theory=self.theory,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/arc/home/Fmajidi/.local/lib/python3.11/site-packages/cobaya/likelihood.py", line 276, in __init__
    self.add_instance(name, like_class(info, packages_path=packages_path,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/arc/home/Fmajidi/.local/lib/python3.11/site-packages/cobaya/likelihood.py", line 94, in __init__
    super().__init__(info, name=name, timing=timing,
  File "/arc/home/Fmajidi/.local/lib/python3.11/site-packages/cobaya/theory.py", line 65, in __init__
    super().__init__(info, name=name, timing=timing,
  File "/arc/home/Fmajidi/.local/lib/python3.11/site-packages/cobaya/component.py", line 346, in __init__
    self.initialize()
  File "/arc/home/Fmajidi/.local/lib/python3.11/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 76, in initialize
    except clik.lkl.CError:
           ^^^^^^^^
AttributeError: module 'clik' has no attribute 'lkl'

I would appreciate any help in this regard.
Sincerely,
Fereshteh

**Comment by cmbant** [comment]
Check if you can run clik separately, if not this is a clik issue rather than Cobaya.

The NPIPE likelihoods do not use clik so could try those instead.

**Comment by FereshtehMajidi** [comment]
yeah, but I want to make sure I have installed all the packages because I had difficulty installing them.

**Comment by cmbant** [comment]
So it is a problem with clik?

**Comment by FereshtehMajidi** [comment]
I am not sure if it's a problem with clik or I need to install other packages.

**Comment by cmbant** [comment]
Try loading/running clik separately (see clik docs for examples).  I'll close assuming it is a clik issue, but can reopen if not.

(I will try to update the cosmo_basic yaml examples to use NPIPE..)
