### ISSUE TITLE
Cobaya cannot load info dictionary

### ISSUE THREAD

**Issue by gcanasherrera** [CobayaSampler/cobaya#383]
Dear @cmbant @JesusTorrado,

I have encountered for the very first time a very weird error when running cobaya in a new machine that never saw before. I pip install cobaya as usual, and it does not complain when I import it. However, when I try to simply run the gaussian example, I get the following error.

```
ketelmeer [203] > python
Python 3.11.5 (main, Jan  4 2024, 11:01:42) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cobaya
>>> info = {
...     "likelihood": {
...         "gaussian_mixture": {
...             "means": [0.2, 0],
...             "covs": [[0.1, 0.05],
...                      [0.05, 0.2]],
...             "derived": True}},
...     "params": dict([
...         ("a", {
...             "prior": {"min": -0.5, "max": 3},
...             "latex": r"\alpha"}),
...         ("b", {
...             "prior": {"dist": "norm", "loc": 0, "scale": 1},
...             "ref": 0,
...             "proposal": 0.5,
...             "latex": r"\beta"}),
...         ("derived_a", {
...             "latex": r"\alpha^\prime"}),
...         ("derived_b", {
...             "latex": r"\beta^\prime"})]),
...     "sampler": {
...         "mcmc": None}}
>>> cobaya.run(info)
[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/canasherrera/.local/lib/python3.11/site-packages/cobaya/run.py", line 123, in run
    with Model(updated_info["params"], updated_info["likelihood"],
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/canasherrera/.local/lib/python3.11/site-packages/cobaya/model.py", line 247, in __init__
    self.likelihood = LikelihoodCollection(info_likelihood, theory=self.theory,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/canasherrera/.local/lib/python3.11/site-packages/cobaya/likelihood.py", line 276, in __init__
    self.add_instance(name, like_class(info, packages_path=packages_path,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/canasherrera/.local/lib/python3.11/site-packages/cobaya/likelihood.py", line 94, in __init__
    super().__init__(info, name=name, timing=timing,
  File "/home/canasherrera/.local/lib/python3.11/site-packages/cobaya/theory.py", line 65, in __init__
    super().__init__(info, name=name, timing=timing,
  File "/home/canasherrera/.local/lib/python3.11/site-packages/cobaya/component.py", line 348, in __init__
    self.packages_path = packages_path or resolve_packages_path()
                                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/canasherrera/.local/lib/python3.11/site-packages/cobaya/tools.py", line 1043, in resolve_packages_path
    return os.environ.get(packages_path_env) or load_packages_path_from_config_file()
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/canasherrera/.local/lib/python3.11/site-packages/cobaya/tools.py", line 1004, in load_packages_path_from_config_file
    return load_config_file().get(packages_path_input)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
-------------------------------------------------------------
```

I'm running out of possible ideas, any suggestion for trouble-shooting?

**Comment by cmbant** [comment]
What's in your global config file that it just tried to read?

**Comment by gcanasherrera** [comment]
In principle, there shouldn't be any global config file. I haven't used cobaya-install to install anything, I literally only did `pip install cobaya` and tried the gaussian example in the docs. 

Debug: True doesn't return any more info. What's the variable I should print within cobaya source code to figure out the config file it's trying to load?

**Comment by cmbant** [comment]
See load_config_file() source for the file name it constructs.

**Comment by gcanasherrera** [comment]
Just digging a bit more info:

```
ketelmeer [115] > cobaya-install --show-packages-path
Traceback (most recent call last):
  File "/home/canasherrera/.local/bin/cobaya-install", line 8, in <module>
    sys.exit(install_script())
             ^^^^^^^^^^^^^^^^
  File "/home/canasherrera/.local/lib/python3.11/site-packages/cobaya/install.py", line 594, in install_script
    output_show_packages_path = resolve_packages_path()
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/canasherrera/.local/lib/python3.11/site-packages/cobaya/tools.py", line 1043, in resolve_packages_path
    return os.environ.get(packages_path_env) or load_packages_path_from_config_file()
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/canasherrera/.local/lib/python3.11/site-packages/cobaya/tools.py", line 1004, in load_packages_path_from_config_file
    return load_config_file().get(packages_path_input)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by cmbant** [comment]
Not sure how an empty file could result, looks like it must have come from the install() function being called sometime

**Comment by cmbant** [comment]
Still not sure how it happens, but changed to return empty dict in this case, which hopefully leads to more helpful error message
https://github.com/CobayaSampler/cobaya/commit/8eb34eb052cf402ea9c0b86b2b61ef4cd39a036e
