### ISSUE TITLE
MPI checking

### ISSUE THREAD

**Issue by cmbant** [CobayaSampler/cobaya#68]
On the cambridge cluster MPI fails after a while with 

```

  File "/home/aml1005/git/cobaya/cobaya/samplers/mcmc/mcmc.py", line 582, in check_all_ready
    np.array([1.]), self.all_ready)
  File "mpi4py/MPI/Comm.pyx", line 826, in mpi4py.MPI.Comm.Iallgather
NotImplementedError
```

We should try to fail at start if this will happen, give more helpful error, and maybe workaround c.f. https://github.com/william-dawson/NTPoly/issues/62

**Comment by cmbant** [comment]
Have added error if  `_mpi.Get_version()[0] < 3`? Still problems on systems with mpi and OK version, but MPI not actually usable (e.g. get hang on head node).

**Comment by PoulinV** [comment]
Dear @cmbant @JesusTorrado,
I hope you are safe and sound!

I am new cobaya and I am getting the same error on my cluster, eventhough I am using an older version of mpi:

MPICH Version:    	3.2
MPICH Release date:	Wed Nov 11 22:06:48 CST 2015
MPICH Device:    	ch3:nemesis
MPICH configure: 	--prefix=/softdec/mpich/
MPICH CC: 	gcc    -O2
MPICH CXX: 	g++   -O2
MPICH F77: 	gfortran   -O2
MPICH FC: 	gfortran   -O2

it seems to happen right after writing a checkpoint:


[0 : mcmc] Checkpoint: 240 samples accepted.
[0 : exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/datadec/users/users/vpoulin/.local/bin//cobaya-run", line 8, in <module>
    sys.exit(run_script())
  File "/dec/users/vpoulin/.local/lib/python2.7/site-packages/cobaya/run.py", line 154, in run_script
    run(info)
  File "/dec/users/vpoulin/.local/lib/python2.7/site-packages/cobaya/run.py", line 87, in run
    sampler.run()
  File "/dec/users/vpoulin/.local/lib/python2.7/site-packages/cobaya/samplers/mcmc/mcmc.py", line 352, in run
    if self.check_all_ready():
  File "/dec/users/vpoulin/.local/lib/python2.7/site-packages/cobaya/samplers/mcmc/mcmc.py", line 562, in check_all_ready
    np.array([1.]), self.all_ready)
  File "mpi4py/MPI/Comm.pyx", line 826, in mpi4py.MPI.Comm.Iallgather
NotImplementedError
-------------------------------------------------------------

[0 : exception handler] Some unexpected ERROR occurred. You can see the exception information above.

Did you ever find a way to solve that bug? Also, alternatively, is there a way to start several chains without using MPI? 

many thanks for your help!
cheers
Vivian

**Comment by cmbant** [comment]
Please try the devel branch - soon to be released major new version.

**Comment by cmbant** [comment]
But if your mpi does not support iallgather you made need to use more recent version (3+)

**Comment by PoulinV** [comment]
Many thanks! I will try that now.
